### ISSUE TITLE
Make use of git rather than just hosting the zip file

### ISSUE THREAD

**Issue by hlqkj** [daviddoesminetest/Minerdream_mod#1]
Hello, it would be great if you could use git directly on the source code, rather that just use it to host the release zip files... Would be of much help for us to fork the mod and pull updates when they are released.
Great job btw, thanks! :)

Edit: you could always keep the zip file as a github 'Release'

**Comment by hlqkj** [comment]
Seems David doesn't do minetest anymore...

**Comment by daviddoesminetest** [comment]
Occasionally I might return to MT for some time... But I don't think I will continue working on MinerDream

**Comment by hlqkj** [comment]
That's sad. This is in my opinion a very nice mod and the textures are great!

Not that it's worth to me (I already have my private fork of this) but you may consider to hand the mod over to the [minetest-mods](https://github.com/minetest-mods) working group instead of dropping it completely: someone may be interested in maintaining it! :)
